apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: dash-enum-bmf-clnt-tp-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: dash-enum-bmf-clnt-tp-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/bmf_client
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/bmf_client
